// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://cknydpndojctryxwrrmq.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImNrbnlkcG5kb2pjdHJ5eHdycm1xIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTEwMzczNzMsImV4cCI6MjA2NjYxMzM3M30.lAU68rRvQPGUT4J6HyF537MxeoYLXG6XcKjzU7ZzRSI";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});